### ISSUE TITLE
On select devices, Android apps with Joda-Time as a dependency won't install

### ISSUE THREAD

**Issue by TheIronMarx** [JodaOrg/joda-time#286]
This may be a little cryptic, but I'll try to be as specific as possible. The issue I'm experiencing is at least writing a ticket about.

When attempting to install Applications via .apk download (this excludes pushing code to device from Android Studio and remains untested on apps coming from Google Play), the installing dialog gets as far as telling me it's installing with a progress bar, but then finishes with "App not installed." error. I have tested and successfully reproduced this issue several .apks. The ones with Joda-time as Gradle dependencies always fail in this manner on these specific devices.

I have never seen this happen before with Joda-Time and any combination of devices and apps, which is frankly a lot. I have also never seen this happen with any other library.

Joda-time releases this is occurring on are (at least) `2.3`, `2.7`, and `2.8`.

The devices in question are
1. ASUS Tablet, Model ME173x running Android 4.2.2 Jellybean.
2. Samsung phone, Model Galaxy Nexus running Android 4.2.2 Jellybean.

Looking at the devices' logs, I see a consistent error and string. I'll paste two instances of this issue.
```
Exception reading res/drawable-hdpi-v4/address.png in /data/app/vmdl-879103662.tmp
    java.lang.SecurityException: META-INF/CERT.SF has invalid digest for org/joda/time/tz/data/America/Argentina/Tucuman in /data/app/vmdl-879103662.tmp
            at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:131)
            at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:350)
            at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:258)
            at java.util.jar.JarFile.getInputStream(JarFile.java:378)
            at android.content.pm.PackageParser.loadCertificates(PackageParser.java:450)
            at android.content.pm.PackageParser.collectCertificates(PackageParser.java:641)
            at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:8520)
            at com.android.server.pm.PackageManagerService.access$2200(PackageManagerService.java:185)
            at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:6390)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:153)
            at android.os.HandlerThread.run(HandlerThread.java:60)
06-06 12:31:55.719      461-484/? E/PackageParser﹕ Package com.secret.package has no certificates at entry res/drawable-hdpi-v4/address.png; ignoring!
```

```
06-05 16:19:20.961      372-391/? W/PackageParser﹕ Exception reading assets/sprite_check.png in /data/app/vmdl-1783207272.tmp
    java.lang.SecurityException: META-INF/CERT.SF has invalid digest for org/joda/time/tz/data/America/Argentina/Tucuman in /data/app/vmdl-1783207272.tmp
            at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:131)
            at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:350)
            at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:258)
            at java.util.jar.JarFile.getInputStream(JarFile.java:378)
            at android.content.pm.PackageParser.loadCertificates(PackageParser.java:446)
            at android.content.pm.PackageParser.collectCertificates(PackageParser.java:634)
            at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:7859)
            at com.android.server.pm.PackageManagerService.access$1900(PackageManagerService.java:172)
            at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:5995)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
06-05 16:19:20.961      372-391/? E/PackageParser﹕ Package com.different.secret.package has no certificates at entry assets/sprite_check.png; ignoring!
```

Once, I received a error slightly different. This one had a warning level of `error`, whereas the other two had a warning level of `warning`.
```
06-05 16:27:21.563    6624-9367/? E/Finsky﹕ [589] CertificateUtils.collectCertificates: Error while collecting certificates
    java.lang.SecurityException: META-INF/CERT.SF has invalid digest for org/joda/time/tz/data/America/Argentina/Tucuman in /storage/emulated/0/Download/name-of-my-application-plus-version.number.apk
            at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:131)
            at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:350)
            at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:258)
            at java.util.jar.JarFile.getInputStream(JarFile.java:378)
            at com.google.android.vending.verifier.CertificateUtils.loadCertificates(CertificateUtils.java:57)
            at com.google.android.vending.verifier.CertificateUtils.collectCertificates(CertificateUtils.java:24)
            at com.google.android.vending.verifier.PackageVerificationService.getPackageInfo(PackageVerificationService.java:986)
            at com.google.android.vending.verifier.PackageVerificationService.access$000(PackageVerificationService.java:67)
            at com.google.android.vending.verifier.PackageVerificationService$WorkerTask.doInBackground(PackageVerificationService.java:371)
            at com.google.android.vending.verifier.PackageVerificationService$WorkerTask.doInBackground(PackageVerificationService.java:350)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
```

Another interesting note is that the error seems to be tripping up on a given file in assets/ or res/, but those don't belong to the applications themselves. I have no idea where they come from. 

The recurring String that exists in all of these Logs are the message with the `SecurityException`, which is `META-INF/CERT.SF has invalid digest for org/joda/time/tz/data/America/Argentina/Tucuman`.

A simple search revealed somebody else having this issue posted to a Gist.  It is dated late 2011. https://gist.github.com/skayred/1403312

Again, I'm not sure if this even is a Joda-time issue, but it at least constitutes a heads up. Let me know if you have any questions I may be able to help with.

**Comment by dlew** [comment]
I'm curious: Does this problem still present itself if you're using [joda-time-android](https://github.com/dlew/joda-time-android)?

**Comment by TheIronMarx** [comment]
Pardon the slow response, I'm working on it!

**Comment by TheIronMarx** [comment]
This problem does persist when I drop in joda-time-android:2.8.0

**Comment by dlew** [comment]
Could it be somehow related to this old issue with compiling with JDK 7? http://stackoverflow.com/a/8037732/60261

**Comment by TheIronMarx** [comment]
We're looking into some signing/digest configurations.

**Comment by TheIronMarx** [comment]
I'm not really sure where to leave this for now. We did update some jar signing code, and it did seem to correct the issue. Again, I'm not really sure where this leaves the issue we originally encountered, or why it has a correlation with joda-time. If I discover anything else, I'll report back.
