### ISSUE TITLE
scala compile error for jdk version

### ISSUE THREAD

**Issue by shijinkui** [JodaOrg/joda-time#289]
cause by `DateTimeZone.forID("Asia/Tokyo")`

[ERROR] 
     while compiling: TimeTest.scala
        during phase: refchecks
     library version: version 2.10.4
    compiler version: version 2.10.4

  last tree to typer: Ident(x)
              symbol: value x (flags: <param> <synthetic>)
   symbol definition: x: Seq[Seq[T]]
                 tpe: Seq[Seq[T]]
       symbol owners: value x
      context owners: object TimeTest -> package <empty>

== Enclosing template or block ==

Template( // val <local TimeTest>: <notype> in object TimeTest, tree.tpe=TimeTest.type
  "java.lang.Object" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 3 statements
  DefDef( // def <init>(): TimeTest.type in object TimeTest
    <method>
    "<init>"
    []
    List(Nil)
    <tpt> // tree.tpe=TimeTest.type
    Block( // tree.tpe=Unit
      Apply( // def <init>(): Object in class Object, tree.tpe=Object
        TimeTest.super."<init>" // def <init>(): Object in class Object, tree.tpe=()Object
        Nil
      )
      ()
    )
  )
  DefDef( // def main(args: Array[String]): Unit in object TimeTest
    <method>
    "main"
    []
    // 1 parameter list
    ValDef( // args: Array[String]
      <param>
      "args"
      <tpt> // tree.tpe=Array[String]
      <empty>
    )
    <tpt> // tree.tpe=Unit
    Block( // tree.tpe=Unit
      ValDef( // val zone: org.joda.time.DateTimeZone
        0
        "zone"
        <tpt> // tree.tpe=org.joda.time.DateTimeZone
        Apply( // def forID(x$1: String): org.joda.time.DateTimeZone in object DateTimeZone, tree.tpe=org.joda.time.DateTimeZone
          "org"."joda"."time"."DateTimeZone"."forID" // def forID(x$1: String): org.joda.time.DateTimeZone in object DateTimeZone, tree.tpe=(x$1: String)org.joda.time.DateTimeZone
          "Asia/Tokyo"
        )
      )
      ()
    )
  )
  DefDef( // def javaTime: Unit in object TimeTest
    <method>
    "javaTime"
    []
    Nil
    <tpt> // tree.tpe=Unit
    Block( // tree.tpe=Unit
      // 7 statements
      Apply( // override def foreach[U](f: A => U): Unit in trait IndexedSeqOptimized, tree.tpe=Unit
        TypeApply( // override def foreach[U](f: A => U): Unit in trait IndexedSeqOptimized, tree.tpe=(f: String => Unit)Unit
          scala.this.Predef.refArrayOps[String](scala.this.Predef.refArrayOps[String](java.util.TimeZone.getAvailableIDs()).sorted[String](math.this.Ordering.String))."foreach" // override def foreach[U](f: A => U): Unit in trait IndexedSeqOptimized, tree.tpe=[U](f: String => U)Unit
          <tpt> // tree.tpe=Unit
        )
        Function( // val $anonfun: <notype>, tree.tpe=String => Unit
          ValDef( // tz: String
            <param> <triedcooking>
            "tz"
            <tpt> // tree.tpe=String
            <empty>
          )
          Block( // tree.tpe=Unit
            // 5 statements
            ValDef( // val cal: java.util.Calendar
              <triedcooking>
              "cal"
              <tpt> // tree.tpe=java.util.Calendar
              Apply( // def getInstance(x$1: java.util.TimeZone): java.util.Calendar in object Calendar, tree.tpe=java.util.Calendar
                "java"."util"."Calendar"."getInstance" // def getInstance(x$1: java.util.TimeZone): java.util.Calendar in object Calendar, tree.tpe=(x$1: java.util.TimeZone)java.util.Calendar
                Apply( // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=java.util.TimeZone
                  "java"."util"."TimeZone"."getTimeZone" // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=(x$1: String)java.util.TimeZone
                  "tz" // tz: String, tree.tpe=String
                )
              )
            )
            Apply( // def setTimeZone(x$1: java.util.TimeZone): Unit in class Calendar, tree.tpe=Unit
              "cal"."setTimeZone" // def setTimeZone(x$1: java.util.TimeZone): Unit in class Calendar, tree.tpe=(x$1: java.util.TimeZone)Unit
              Apply( // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=java.util.TimeZone
                "java"."util"."TimeZone"."getTimeZone" // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=(x$1: String)java.util.TimeZone
                "tz" // tz: String, tree.tpe=String
              )
            )
            ValDef( // val fmt: java.text.SimpleDateFormat
              <triedcooking>
              "fmt"
              <tpt> // tree.tpe=java.text.SimpleDateFormat
              Apply( // def <init>(x$1: String): java.text.SimpleDateFormat in class SimpleDateFormat, tree.tpe=java.text.SimpleDateFormat
                new java.text.SimpleDateFormat."<init>" // def <init>(x$1: String): java.text.SimpleDateFormat in class SimpleDateFormat, tree.tpe=(x$1: String)java.text.SimpleDateFormat
                "yyyy-MM-dd HH:mm:ss Z"
              )
            )
            Apply( // def setTimeZone(x$1: java.util.TimeZone): Unit in class DateFormat, tree.tpe=Unit
              "fmt"."setTimeZone" // def setTimeZone(x$1: java.util.TimeZone): Unit in class DateFormat, tree.tpe=(x$1: java.util.TimeZone)Unit
              Apply( // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=java.util.TimeZone
                "java"."util"."TimeZone"."getTimeZone" // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=(x$1: String)java.util.TimeZone
                "tz" // tz: String, tree.tpe=String
              )
            )
            ValDef( // val str: String
              <triedcooking>
              "str"
              <tpt> // tree.tpe=String
              Apply( // final def format(x$1: java.util.Date): String in class DateFormat, tree.tpe=String
                "fmt"."format" // final def format(x$1: java.util.Date): String in class DateFormat, tree.tpe=(x$1: java.util.Date)String
                Apply( // final def getTime(): java.util.Date in class Calendar, tree.tpe=java.util.Date
                  "cal"."getTime" // final def getTime(): java.util.Date in class Calendar, tree.tpe=()java.util.Date
                  Nil
                )
              )
            )
            Apply( // def println(x: Any): Unit in object Predef, tree.tpe=Unit
              scala.this."Predef"."println" // def println(x: Any): Unit in object Predef, tree.tpe=(x: Any)Unit
              Apply( // final def +(x$1: Any): String in class String, tree.tpe=String
                str.+("  ==>  ").+(tz).+("||")."$plus" // final def +(x$1: Any): String in class String, tree.tpe=(x$1: Any)String
                Apply( // def parse(x$1: String): java.util.Date in class DateFormat, tree.tpe=java.util.Date
                  "fmt"."parse" // def parse(x$1: String): java.util.Date in class DateFormat, tree.tpe=(x$1: String)java.util.Date
                  "str" // val str: String, tree.tpe=String
                )
              )
            )
          )
        )
      )
      ValDef( // val f: java.text.SimpleDateFormat
        <triedcooking>
        "f"
        <tpt> // tree.tpe=java.text.SimpleDateFormat
        Apply( // def <init>(x$1: String): java.text.SimpleDateFormat in class SimpleDateFormat, tree.tpe=java.text.SimpleDateFormat
          new java.text.SimpleDateFormat."<init>" // def <init>(x$1: String): java.text.SimpleDateFormat in class SimpleDateFormat, tree.tpe=(x$1: String)java.text.SimpleDateFormat
          "dd-MM-yyyy HH:mm:SS Z"
        )
      )
      Apply( // def setTimeZone(x$1: java.util.TimeZone): Unit in class DateFormat, tree.tpe=Unit
        "f"."setTimeZone" // def setTimeZone(x$1: java.util.TimeZone): Unit in class DateFormat, tree.tpe=(x$1: java.util.TimeZone)Unit
        Apply( // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=java.util.TimeZone
          "java"."util"."TimeZone"."getTimeZone" // def getTimeZone(x$1: String): java.util.TimeZone in object TimeZone, tree.tpe=(x$1: String)java.util.TimeZone
          "UTC"
        )
      )
      ValDef( // val cal: java.util.Calendar
        <triedcooking>
        "cal"
        <tpt> // tree.tpe=java.util.Calendar
        Apply( // def getInstance(): java.util.Calendar in object Calendar, tree.tpe=java.util.Calendar
          "java"."util"."Calendar"."getInstance" // def getInstance(): java.util.Calendar in object Calendar, tree.tpe=()java.util.Calendar
          Nil
        )
      )
      Apply( // def println(x: Any): Unit in object Predef, tree.tpe=Unit
        scala.this."Predef"."println" // def println(x: Any): Unit in object Predef, tree.tpe=(x: Any)Unit
        Apply( // final def format(x$1: java.util.Date): String in class DateFormat, tree.tpe=String
          "f"."format" // final def format(x$1: java.util.Date): String in class DateFormat, tree.tpe=(x$1: java.util.Date)String
          Apply( // final def getTime(): java.util.Date in class Calendar, tree.tpe=java.util.Date
            "cal"."getTime" // final def getTime(): java.util.Date in class Calendar, tree.tpe=()java.util.Date
            Nil
          )
        )
      )
      Apply( // def println(x: Any): Unit in object Predef, tree.tpe=Unit
        scala.this."Predef"."println" // def println(x: Any): Unit in object Predef, tree.tpe=(x: Any)Unit
        Apply( // def <init>(): java.util.Date in class Date, tree.tpe=java.util.Date
          new java.util.Date."<init>" // def <init>(): java.util.Date in class Date, tree.tpe=()java.util.Date
          Nil
        )
      )
      Apply( // def println(x: Any): Unit in object Predef, tree.tpe=Unit
        scala.this."Predef"."println" // def println(x: Any): Unit in object Predef, tree.tpe=(x: Any)Unit
        Apply( // def getTimeInMillis(): Long in class Calendar, tree.tpe=Long
          "cal"."getTimeInMillis" // def getTimeInMillis(): Long in class Calendar, tree.tpe=()Long
          Nil
        )
      )
      Apply( // def println(x: Any): Unit in object Predef, tree.tpe=Unit
        scala.this."Predef"."println" // def println(x: Any): Unit in object Predef, tree.tpe=(x: Any)Unit
        Apply( // def currentTimeMillis(): Long in object System, tree.tpe=Long
          java.this."lang"."System"."currentTimeMillis" // def currentTimeMillis(): Long in object System, tree.tpe=()Long
          Nil
        )
      )
    )
  )
)

== Expanded type of tree ==

AliasTypeRef(
  Alias(type Seq[+A] = Seq[A])
  args = List(
    AliasTypeRef(
      Alias(type Seq[+A] = Seq[A])
      args = List(SkolemTypeRef(TypeSkolem(T)))
      normalize = TypeRef(
        TypeSymbol(
          abstract trait Seq[+A] extends PartialFunction[Int,A] with Iterable[A] with GenSeq[A] with GenericTraversableTemplate[A,Seq] with SeqLike[A,Seq[A]]
          
        )
        args = List(SkolemTypeRef(TypeSkolem(T)))
      )
    )
  )
  normalize = TypeRef(
    TypeSymbol(
      abstract trait Seq[+A] extends PartialFunction[Int,A] with Iterable[A] with GenSeq[A] with GenericTraversableTemplate[A,Seq] with SeqLike[A,Seq[A]]
      
    )
    args = List(
      AliasTypeRef(
        Alias(type Seq[+A] = Seq[A])
        args = List(SkolemTypeRef(TypeSkolem(T)))
        normalize = TypeRef(
          TypeSymbol(
            abstract trait Seq[+A] extends PartialFunction[Int,A] with Iterable[A] with GenSeq[A] with GenericTraversableTemplate[A,Seq] with SeqLike[A,Seq[A]]
            
          )
          args = List(SkolemTypeRef(TypeSkolem(T)))
        )
      )
    )
  )
)

uncaught exception during compilation: java.lang.AssertionError
---------------------------------------------------
constituent[0]: /plugins/maven/lib/maven3/lib/aether-api-1.13.1.jar
constituent[1]: /plugins/maven/lib/maven3/lib/aether-connector-wagon-1.13.1.jar
constituent[2]: /plugins/maven/lib/maven3/lib/aether-impl-1.13.1.jar
constituent[3]: /plugins/maven/lib/maven3/lib/aether-spi-1.13.1.jar
constituent[4]: /plugins/maven/lib/maven3/lib/aether-util-1.13.1.jar
constituent[5]: /plugins/maven/lib/maven3/lib/commons-cli-1.2.jar
constituent[6]: /plugins/maven/lib/maven3/lib/commons-io-2.2.jar
constituent[7]: /plugins/maven/lib/maven3/lib/commons-lang-2.6.jar
constituent[8]: /plugins/maven/lib/maven3/lib/maven-aether-provider-3.0.5.jar
constituent[9]: /plugins/maven/lib/maven3/lib/maven-artifact-3.0.5.jar
constituent[10]: /plugins/maven/lib/maven3/lib/maven-compat-3.0.5.jar
constituent[11]: /plugins/maven/lib/maven3/lib/maven-core-3.0.5.jar
constituent[12]: /plugins/maven/lib/maven3/lib/maven-embedder-3.0.5.jar
constituent[13]: /plugins/maven/lib/maven3/lib/maven-model-3.0.5.jar
constituent[14]: /plugins/maven/lib/maven3/lib/maven-model-builder-3.0.5.jar
constituent[15]: /plugins/maven/lib/maven3/lib/maven-plugin-api-3.0.5.jar
Exception in thread "main" java.lang.AssertionError: assertion failed: org.joda.convert.FromString
constituent[16]: /plugins/maven/lib/maven3/lib/maven-repository-metadata-3.0.5.jar
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1212)
constituent[17]: /plugins/maven/lib/maven3/lib/maven-settings-3.0.5.jar
	at scala.reflect.internal.Symbols$TypeSymbol.isNonBottomSubClass(Symbols.scala:2821)
constituent[18]: /plugins/maven/lib/maven3/lib/maven-settings-builder-3.0.5.jar
	at scala.reflect.internal.AnnotationInfos$AnnotationInfo.matches(AnnotationInfos.scala:295)
	at scala.reflect.internal.AnnotationInfos$Annotatable$class.dropOtherAnnotations(AnnotationInfos.scala:65)
	at scala.reflect.internal.AnnotationInfos$Annotatable$class.hasAnnotation(AnnotationInfos.scala:50)
	at scala.reflect.internal.Symbols$Symbol.hasAnnotation(Symbols.scala:112)
constituent[19]: /plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar
	at scala.reflect.internal.Symbols$Symbol.isDeprecated(Symbols.scala:723)
constituent[20]: /plugins/maven/lib/maven3/lib/plexus-component-annotations-1.5.5.jar
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkDeprecated(RefChecks.scala:1385)
constituent[21]: /plugins/maven/lib/maven3/lib/plexus-interpolation-1.14.jar
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformSelect(RefChecks.scala:1648)
constituent[22]: /plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1814)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:96)
constituent[23]: /plugins/maven/lib/maven3/lib/plexus-utils-2.0.6.jar
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1219)
constituent[24]: /plugins/maven/lib/maven3/lib/sisu-guava-0.9.9.jar
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
constituent[25]: /plugins/maven/lib/maven3/lib/sisu-guice-3.1.0-no_aop.jar
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
constituent[26]: /plugins/maven/lib/maven3/lib/sisu-inject-bean-2.3.0.jar
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
constituent[27]: /plugins/maven/lib/maven3/lib/sisu-inject-plexus-2.3.0.jar
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
constituent[28]: /plugins/maven/lib/maven3/lib/wagon-file-2.8.jar
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:96)
constituent[29]: /plugins/maven/lib/maven3/lib/wagon-http-2.8-shaded.jar
	at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1229)
constituent[30]: /plugins/maven/lib/maven3/lib/wagon-http-shared-2.8.jar
	at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1228)
constituent[31]: /plugins/maven/lib/maven3/lib/wagon-provider-api-2.8.jar
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
---------------------------------------------------
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1227)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1337)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1268)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1268)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1268)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:96)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1238)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:96)
	at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1235)
	at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1233)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1232)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1349)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1268)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1268)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1268)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:96)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1276)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:96)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:96)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.eliminateModuleDefs(RefChecks.scala:1316)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1335)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1268)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1268)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1268)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:96)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1841)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:96)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:90)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:72)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:73)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:35)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:29)
	at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:71)
	at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:71)
	at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:71)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:101)
	at sbt.compiler.AggressiveCompile$$anonfun$4.compileScala$1(AggressiveCompile.scala:70)
	at sbt.compiler.AggressiveCompile$$anonfun$4.apply(AggressiveCompile.scala:88)
	at sbt.compiler.AggressiveCompile$$anonfun$4.apply(AggressiveCompile.scala:60)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:24)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:22)
	at sbt.inc.Incremental$.cycle(Incremental.scala:52)
	at sbt.inc.Incremental$.compile(Incremental.scala:29)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:20)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:96)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:44)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:158)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:142)
	at sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:77)
	at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:308)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:124)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:104)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by jodastephen** [comment]
This isn't really a bug report or something that can be actioned. See [sscce](http://sscce.org/).
