### ISSUE TITLE
Midnight is not accepted

### ISSUE THREAD

**Issue by lastcmaster** [JodaOrg/joda-time#292]
According to ISO 8601 (see attached screenshots from standard), midnight can be represented as [00:00:00] or [24:00:00] but Joda-Time throws an exception on the later format.
![screen shot 2015-06-15 at 11 23 04](https://cloud.githubusercontent.com/assets/5843038/8156959/1676d6f6-1351-11e5-8d8f-adc6c2463423.png)
![screen shot 2015-06-15 at 11 23 15](https://cloud.githubusercontent.com/assets/5843038/8156958/167505ec-1351-11e5-830c-535667277569.png)

org.joda.time.IllegalFieldValueException: Cannot parse "2010-07-02T24:00:00": Value 24 for hourOfDay must be in the range [0,23]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)
	at org.joda.time.field.PreciseDateTimeField.set(PreciseDateTimeField.java:112)
	at org.joda.time.format.DateTimeParserBucket$SavedField.set(DateTimeParserBucket.java:568)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:447)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:411)
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:882)

**Comment by jodastephen** [comment]
Joda-Time does not support creating a `LocalTime` with the value 24:00.

See also [this answer](http://stackoverflow.com/a/5388148/38896).
