### ISSUE TITLE
Datetime fails to parse its own output when epoch = Long.MAX_VALUE (again !)

### ISSUE THREAD

**Issue by martin-a** [JodaOrg/joda-time#297]
Hello, thank for the fix on #100 
Unfortunately the check introduced  seems to work for only for `long` type, not for `Long` object, which causes the problem to reproduce

```DateTime.parse(new DateTime(Long.valueOf(Long.MAX_VALUE)).toString());```

throws this exception:
```
org.joda.time.IllegalFieldValueException: Cannot parse "292278994-08-17T07:12:55.807Z": Value 292278994 for year must be in the range [-292275054,292278993]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)
	at org.joda.time.chrono.BasicYearDateTimeField.set(BasicYearDateTimeField.java:83)
	at org.joda.time.format.DateTimeParserBucket$SavedField.set(DateTimeParserBucket.java:568)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:447)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:411)
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:882)
	at org.joda.time.DateTime.parse(DateTime.java:160)
	at org.joda.time.DateTime.parse(DateTime.java:149)
```

**Comment by mstevens83** [comment]
I'm not sure but could it be that PR #315 tackles (part of) this problem, and/or issue #190?

**Comment by jodastephen** [comment]
Try the [min/max branch](https://github.com/JodaOrg/joda-time/commits/topic/minmax). I won't merge the changes unless I hear they are suitable.

**Comment by mstevens83** [comment]
Please read: https://github.com/JodaOrg/joda-time/issues/190#issuecomment-148007978
