### ISSUE TITLE
NullPointerException in deserialized CachedDateTimeZone.getInfo

### ISSUE THREAD

**Issue by cchepelov** [JodaOrg/joda-time#307]
Attempting to format to string deserialized instances of DateTime (originally obtained from an HBase instance and then shipped around via scalding-cascading-(kryo?)-tez) results in the following stack:

    Caused by: java.lang.NullPointerException
            at org.joda.time.tz.CachedDateTimeZone.getInfo(CachedDateTimeZone.java:143)
            at org.joda.time.tz.CachedDateTimeZone.getOffset(CachedDateTimeZone.java:103)
            at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:676)
            at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:521)
            at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:625)
            at com.transparencyrights.XXXXX$$anonfun$12.apply(XXXXXX.scala:137)
            at com.transparencyrights.XXXXX$$anonfun$12.apply(XXXXXX.scala:137)
            at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
            at scala.collection.Iterator$class.foreach(Iterator.scala:742)
            at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
            at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47)
            at cascading.flow.stream.element.FunctionEachStage.receive(FunctionEachStage.java:100)

Using joda-time 2.7 through nscala-time 2.0.0

Looking at the code here https://github.com/JodaOrg/joda-time/blob/v2.7/src/main/java/org/joda/time/tz/CachedDateTimeZone.java#L145 it seems that the issue is that the "iInfoCache" transient field initialized at https://github.com/JodaOrg/joda-time/blob/v2.7/src/main/java/org/joda/time/tz/CachedDateTimeZone.java#L84 is deserialized as a null. As CachedDateTimeZone lacks a readResolve() method, there is no chance to initialize iInfoCache.

Or is this a duplicate of https://github.com/JodaOrg/joda-time/issues/65, the blame being on the failure from the serialization library to have applied the writeReplace/(serialize a Stub(id))/readResolve protocol ?

**Comment by jodastephen** [comment]
Yes, this will be an issue with the external serialization library. We can only reasonably support the standard serialization spec, and if tools fail to implement it, that is there problem.

**Comment by cchepelov** [comment]
Fair, thanks!
