### ISSUE TITLE
Multiple calls to PeriodFormatterBuilder.toFormatter create different formatters

### ISSUE THREAD

**Issue by judu** [JodaOrg/joda-time#309]
When testing PeriodFormatterBuilder in a scala console, I found myself doing this:

```
scala> val builder = new PeriodFormatterBuilder().printZeroAlways().appendYears().appendSuffix(" years").appendSeparator(" ").appendMonths().appendSuffix(" mons").appendSeparator(" ").appendDays().appendSuffix(" days").appendSeparator(" ").appendHours().appendSuffix(" hours").appendSeparator(" ").appendMinutes().appendSuffix(" mins").appendSeparator(" ").appendSecondsWithMillis().appendSuffix(" secs")
builder: org.joda.time.format.PeriodFormatterBuilder = org.joda.time.format.PeriodFormatterBuilder@39e62cb0

scala> val p = new Period(0,0,0,1,0,0,0,0)
p: org.joda.time.Period = P1D

scala> parser.toFormatter().print(p)
res1: String = 0 years 0 mons 1 days 0 hours 0 mins 0.000 secs

scala> builder.toFormatter().parsePeriod("0 years 0 mons 1 days 0 hours 0 mins 0.000 secs")
java.lang.IllegalArgumentException: Invalid format: "0 years 0 mons 1 days 0 hours 0 mins 0.000 secs" is too short
  at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:330)                            
  at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:308)                                   
  ... 43 elided

scala> builder.toFormatter().print(p)
res2: String = 0 years 0 mons 1 days 0 hours 0 mins 0.000 secs0 mons 1 days 0 hours 0 mins 0.000 secs1 days 0 hours 0 mins 0.000 secs0 hours 0
mins 0.000 secs0 mins 0.000 secs0.000 secs
```

The PeriodFormatterBuilder seems to add each described field to an already built formatter. If I run the `builder.toFormatter().print(p)` many times, it does not add fields anymore. It keeps the malformed formatted in the exact same (malformed) state.

Tested on 2.8.1 and 2.8.2.

**Comment by jodastephen** [comment]
The intention is that `builder.toFormatter()` is only called once, and the builder is then discarded. The formatter produced is then immutable and safe from change. So, while this may be unexpected, it is not standard usage of the API.

**Comment by jodastephen** [comment]
As I suspected, while this could be fixed, the effort of doing so outweighs the benefits.
