### ISSUE TITLE
Joda-time crashing on Samsung SIII

### ISSUE THREAD

**Issue by user-don** [JodaOrg/joda-time#351]
Hi,

I'm on a team of developers using joda-time for an android application. Strangely, our app is now crashing on launch on one of our test devices (a Samsung Galaxy SIII, Android 4.4.2). Works fine on our DROID and S5. We are running version 2.9.1. Our application started crashing on launch due to Joda starting last Friday (1/22/16). Below is the log -- hopefully you guys might be able to provide some insight. I'm not sure what parts of the log will be valuable, so I'm starting from the top. The interesting stuff is at the bottom.

Thanks in advance for any help! You guys do a great job and joda-time is a huge leg-up over Java's package.

```
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/joda/time/format/DateTimeFormatterBuilder;)
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/joda/time/format/DateTimeFormatterBuilder;)
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit E/dalvikvm: Could not find class 'org.joda.time.format.DateTimeFormat$StyleFormatter', referenced from method org.joda.time.format.DateTimeFormat.createDateTimeFormatter
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve new-instance 9443 (Lorg/joda/time/format/DateTimeFormat$StyleFormatter;) in Lorg/joda/time/format/DateTimeFormat;
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x22 at 0x0005
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit E/dalvikvm: Could not find class 'org.joda.time.format.DateTimeFormatterBuilder', referenced from method org.joda.time.format.DateTimeFormat.createFormatterForPattern
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve new-instance 9447 (Lorg/joda/time/format/DateTimeFormatterBuilder;) in Lorg/joda/time/format/DateTimeFormat;
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x22 at 0x001a
01-28 16:47:35.540 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/joda/time/format/DateTimeFormatterBuilder;)
01-28 16:47:35.550 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendEraText, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.550 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65094: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendEraText ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.550 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x003c
01-28 16:47:35.550 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendCenturyOfEra, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.550 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65086: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendCenturyOfEra (II)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.550 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0042
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTwoDigitYear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65113: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTwoDigitYear (IZ)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0075
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTwoDigitWeekyear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65112: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTwoDigitWeekyear (IZ)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0084
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendYearOfEra, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65117: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendYearOfEra (II)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.560 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00ab
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendWeekyear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65115: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendWeekyear (II)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00af
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendYear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65116: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendYear (II)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00b3
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendMonthOfYearText, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65104: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendMonthOfYearText ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00bd
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendMonthOfYearShortText, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65103: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendMonthOfYearShortText ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00c2
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendMonthOfYear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65102: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendMonthOfYear (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.570 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00c7
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendDayOfMonth, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65089: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendDayOfMonth (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00cc
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendHalfdayOfDayText, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65096: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendHalfdayOfDayText ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00d1
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendClockhourOfHalfday, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65088: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendClockhourOfHalfday (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00d6
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendHourOfDay, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65097: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendHourOfDay (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00db
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendClockhourOfDay, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65087: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendClockhourOfDay (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00e0
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendHourOfHalfday, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65098: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendHourOfHalfday (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.580 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00e5
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendMinuteOfHour, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65101: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendMinuteOfHour (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00ea
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendSecondOfMinute, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65106: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendSecondOfMinute (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00ef
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendFractionOfSecond, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65095: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendFractionOfSecond (II)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00f4
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendDayOfWeek, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65090: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendDayOfWeek (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x00f9
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendDayOfWeekText, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65092: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendDayOfWeekText ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0101
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendDayOfWeekShortText, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65091: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendDayOfWeekShortText ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0106
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendDayOfYear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65093: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendDayOfYear (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.590 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x010b
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendWeekOfWeekyear, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65114: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendWeekOfWeekyear (I)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0110
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTimeZoneName, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65108: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTimeZoneName ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0118
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTimeZoneShortName, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65111: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTimeZoneShortName (Ljava/util/Map;)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x011e
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTimeZoneOffset, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65109: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTimeZoneOffset (Ljava/lang/String;Ljava/lang/String;ZII)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x74 at 0x012d
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTimeZoneOffset, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65109: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTimeZoneOffset (Ljava/lang/String;Ljava/lang/String;ZII)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x74 at 0x013c
01-28 16:47:35.600 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendTimeZoneId, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65107: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendTimeZoneId ()Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0141
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendLiteral, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65099: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendLiteral (C)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0157
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit I/dalvikvm: Could not find method org.joda.time.format.DateTimeFormatterBuilder.appendLiteral, referenced from method org.joda.time.format.DateTimeFormat.parsePatternTo
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve virtual method 65100: Lorg/joda/time/format/DateTimeFormatterBuilder;.appendLiteral (Ljava/lang/String;)Lorg/joda/time/format/DateTimeFormatterBuilder;
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x6e at 0x0161
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/joda/time/format/InternalPrinter;)
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit E/dalvikvm: Could not find class 'org.joda.time.format.DateTimeFormat$StyleFormatter', referenced from method org.joda.time.format.DateTimeFormat.patternForStyle
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit W/dalvikvm: VFY: unable to resolve check-cast 9443 (Lorg/joda/time/format/DateTimeFormat$StyleFormatter;) in Lorg/joda/time/format/DateTimeFormat;
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/dalvikvm: VFY: replacing opcode 0x1f at 0x000e
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/dalvikvm: DexOpt: unable to opt direct call 0xfdef at 0x07 in Lorg/joda/time/format/DateTimeFormat;.createDateTimeFormatter
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/dalvikvm: DexOpt: unable to opt direct call 0xfe3d at 0x1c in Lorg/joda/time/format/DateTimeFormat;.createFormatterForPattern
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit D/AndroidRuntime: Shutting down VM
01-28 16:47:35.610 6151-6151/advancetransit.advancetransit W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41799da0)
01-28 16:47:35.620 6151-6151/advancetransit.advancetransit D/HockeyApp: Writing unhandled exception to: /data/data/advancetransit.advancetransit/files/ca1894c1-c19a-49ea-acbe-bf74fc934521.stacktrace
01-28 16:47:35.620 6151-6151/advancetransit.advancetransit E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: advancetransit.advancetransit, PID: 6151
                                                                             java.lang.NoClassDefFoundError: org.joda.time.format.DateTimeFormatterBuilder
                                                                                 at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:686)
                                                                                 at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177)
                                                                                 at advancetransit.advancetransit.models.StopTime.timeDifference(StopTime.java:116)
                                                                                 at advancetransit.advancetransit.ui.activities.MainActivity.onStopSelect(MainActivity.java:1678)
                                                                                 at advancetransit.advancetransit.ui.activities.MainActivity$GetLiveData.onPostExecute(MainActivity.java:970)
                                                                                 at advancetransit.advancetransit.ui.activities.MainActivity$GetLiveData.onPostExecute(MainActivity.java:785)
                                                                                 at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                                 at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                                 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:146)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5487)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
01-28 16:47:38.974 6151-6158/advancetransit.advancetransit I/AndroidRuntime: VM exiting with result code 1, cleanup skipped.
```

**Comment by jodastephen** [comment]
I don't use or know Android, so won't be able to help. I suspect you'll have more luck on a different forum.

**Comment by user-don** [comment]
Hi Joda,

Thanks for the prompt response, and totally understand. This is a Java project after all, and not Android!

Will update if we end up figuring out what's going wrong

**Comment by yukuoyuan** [comment]
I would like the author to try and solve this problem, thank you

**Comment by yukuoyuan** [comment]
Not the type of problem, as long as the mobile phone Android level 19 will appear this problem

**Comment by yukuoyuan** [comment]
hi body,I solved the problem,  I tried to change to compile 'com.android.support:appcompat-v7:25.0.1'   ,I hope I can help you
