### ISSUE TITLE
new LocalDateTime() throws uncaught runtime exception

### ISSUE THREAD

**Issue by chensb** [JodaOrg/joda-time#359]
the call stack is

Caught: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:157)
        at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
        at org.joda.time.LocalDateTime.<init>(LocalDateTime.java:264)
        at org.zhmj.guard.TaskWrapper.refreshZones(TaskWrapper.java:197)
        at org.zhmj.guard.TaskWrapper.startDeamon(TaskWrapper.java:266)
        at org.zhmj.guard.TaskWrapper$startDeamon.call(Unknown Source)
        at ServerDeamon.run(ServerDeamon.groovy:9)
Caused by: java.lang.RuntimeException: default directory must be absolute
        ... 7 more

java version "1.7.0_80"
ubuntu 14.04

**Comment by jodastephen** [comment]
There is not enough information here for me to be able to comment. It is likely to be a problem with `org.zhmj.guard`. You will have more luck at StackOverflow.
