### ISSUE TITLE
DST DateTimeZone is not properly serializable

### ISSUE THREAD

**Issue by mattinger** [JodaOrg/joda-time#368]
### Key information

- Joda-Time version
2.9.3
- Result of `DateTimeZone.getDefault()`
America/New_York

### Problem description

When trying to serialize the DateTimeZone.forID("America/New_York") in an android vm, i'm getting a serialization error:

Caused by: java.io.NotSerializableException: org.joda.time.tz.DateTimeZoneBuilder$Recurrence
                                                       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)

I believe this has to do with the fact that the private class DSTZone has a reference to
DateTimeZoneBuilder$Recurrence, which is not serializable.

DSTZone is missing a writeReplace method, and i don't believe ObjectOutputStream would
be smart enough to go to it's parent class to find it.  At least not in the android vm.

I have not tried in the standard 1.8 vm.

### Test case

new ObjectOutputStream(new ByteArrayOutputStream()).writeObject(DateTimeZone.forID("America/New_York"));

**Comment by jodastephen** [comment]
Joda-Time is designed to work with the standard Java serialization facilities. If the Android VM does not implement the specification correctly, there is little I can do. Maybe try contacting https://github.com/dlew/joda-time-android ?
