### ISSUE TITLE
Could not find class 'org.joda.time.DateTime', referenced from method com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder.<clinit>

### ISSUE THREAD

**Issue by i-sourabh** [JodaOrg/joda-time#377]
Complete Log:
`06-01 14:59:33.432 27320-27324/org.hispindia.bidtrackerreports D/dalvikvm: GC_CONCURRENT freed 177K, 2% free 14351K/14599K, paused 7ms+6ms
06-01 14:59:33.592 27320-27320/org.hispindia.bidtrackerreports W/dalvikvm: Unable to resolve superclass of Lorg/joda/time/DateTime; (7572)
06-01 14:59:33.592 27320-27320/org.hispindia.bidtrackerreports W/dalvikvm: Link of class 'Lorg/joda/time/DateTime;' failed
06-01 14:59:33.592 27320-27320/org.hispindia.bidtrackerreports E/dalvikvm: Could not find class 'org.joda.time.DateTime', referenced from method com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder.<clinit>
06-01 14:59:33.602 27320-27320/org.hispindia.bidtrackerreports W/dalvikvm: VFY: unable to resolve const-class 7519 (Lorg/joda/time/DateTime;) in Lcom/raizlabs/android/dbflow/config/GeneratedDatabaseHolder;
06-01 14:59:33.602 27320-27320/org.hispindia.bidtrackerreports D/dalvikvm: VFY: replacing opcode 0x1c at 0x003e
06-01 14:59:33.612 27320-27320/org.hispindia.bidtrackerreports W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/raizlabs/android/dbflow/config/GeneratedDatabaseHolder;
06-01 14:59:33.622 27320-27320/org.hispindia.bidtrackerreports D/AndroidRuntime: Shutting down VM
06-01 14:59:33.632 27320-27320/org.hispindia.bidtrackerreports W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x409961f8)
06-01 14:59:33.652 27320-27320/org.hispindia.bidtrackerreports E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 java.lang.RuntimeException: Unable to create application org.hispindia.bidtrackerreports.HIApplication: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3928)
                                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:122)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1184)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:4340)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                                  Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
                                                                                     at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:119)
                                                                                     at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:158)
                                                                                     at org.hisp.dhis.android.sdk.persistence.Dhis2Application.onCreate(Dhis2Application.java:58)
                                                                                     at org.hispindia.bidtrackerreports.HIApplication.onCreate(HIApplication.java:33)
                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3925)
                                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:122) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1184) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:4340) 
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
                                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                                  Caused by: java.lang.ExceptionInInitializerError
                                                                                     at java.lang.Class.classForName(Native Method)
                                                                                     at java.lang.Class.forName(Class.java:217)
                                                                                     at java.lang.Class.forName(Class.java:172)
                                                                                     at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:116)
                                                                                     at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:158) 
                                                                                     at org.hisp.dhis.android.sdk.persistence.Dhis2Application.onCreate(Dhis2Application.java:58) 
                                                                                     at org.hispindia.bidtrackerreports.HIApplication.onCreate(HIApplication.java:33) 
                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969) 
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3925) 
                                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:122) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1184) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:4340) 
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
                                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                                  Caused by: java.lang.NoClassDefFoundError: org.joda.time.DateTime
                                                                                     at com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder.<clinit>(GeneratedDatabaseHolder.java:15)
                                                                                     at java.lang.Class.classForName(Native Method) 
                                                                                     at java.lang.Class.forName(Class.java:217) 
                                                                                     at java.lang.Class.forName(Class.java:172) 
                                                                                     at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:116) 
                                                                                     at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:158) 
                                                                                     at org.hisp.dhis.android.sdk.persistence.Dhis2Application.onCreate(Dhis2Application.java:58) 
                                                                                     at org.hispindia.bidtrackerreports.HIApplication.onCreate(HIApplication.java:33) 
                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969) 
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3925) 
                                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:122) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1184) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:4340) 
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
                                                                                     at dalvik.system.NativeStart.main(Native Method) 
`

**Comment by jodastephen** [comment]
An exception with no context is not suitable as an issue.
