### ISSUE TITLE
Issues on Java 9

### ISSUE THREAD

**Issue by chrisseaton** [JodaOrg/joda-time#394]
### Key information
- Joda-Time version `e6dd4ba04d1e16bbc9c98cfd19f330a15b6fd060`
- Result of `TimeZone.getDefault()` `sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]`
- Result of `DateTimeZone.getDefault()` `Europe/London`
### Problem description

Has anyone been looking at Joda on Java 9? The tests don't seem to pass at the moment.
### Test case

```
$ JAVA_HOME=$JAVA8_HOME PATH=$JAVA8_HOME/bin:$PATH java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
$ JAVA_HOME=$JAVA8_HOME PATH=$JAVA8_HOME/bin:$PATH mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Joda-Time 2.9.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ joda-time ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources to META-INF
[INFO] Copying 15 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ joda-time ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (compile-tzdb) @ joda-time ---
Writing zoneinfo files
Writing ZoneInfoMap
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ joda-time ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 35 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ joda-time ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ joda-time ---
[INFO] Surefire report directory: /Users/chrisseaton/Documents/ruby/joda-time/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.joda.time.TestAllPackages

TestBuddhistChronology.testCalendar

TestCopticChronology.testCalendar

TestEthiopicChronology.testCalendar

TestIslamicChronology.testCalendar

Testing Gregorian chronology over 1000 iterations
100% complete (i=1000)

Testing Julian chronology over 1000 iterations
100% complete (i=1000)
Writing zoneinfo files
Writing ZoneInfoMap
Tests run: 4201, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.84 sec - in org.joda.time.TestAllPackages

Results :

Tests run: 4201, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.817 s
[INFO] Finished at: 2016-10-09T18:54:06+01:00
[INFO] Final Memory: 12M/437M
[INFO] ------------------------------------------------------------------------
```

```
$ JAVA_HOME=$JAVA9_HOME PATH=$JAVA9_HOME/bin:$PATH java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+138)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+138, mixed mode)
$ JAVA_HOME=$JAVA9_HOME PATH=$JAVA9_HOME/bin:$PATH mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Joda-Time 2.9.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ joda-time ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources to META-INF
[INFO] Copying 15 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ joda-time ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (compile-tzdb) @ joda-time ---
Writing zoneinfo files
Writing ZoneInfoMap
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ joda-time ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 35 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ joda-time ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ joda-time ---
[INFO] Surefire report directory: /Users/chrisseaton/Documents/ruby/joda-time/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.joda.time.TestAllPackages

TestBuddhistChronology.testCalendar

TestCopticChronology.testCalendar

TestEthiopicChronology.testCalendar

TestIslamicChronology.testCalendar

Testing Gregorian chronology over 1000 iterations
100% complete (i=1000)

Testing Julian chronology over 1000 iterations
100% complete (i=1000)
Writing zoneinfo files
Writing ZoneInfoMap
Tests run: 4201, Failures: 6, Errors: 2, Skipped: 0, Time elapsed: 3.298 sec <<< FAILURE! - in org.joda.time.TestAllPackages
testGetName_berlin(org.joda.time.TestDateTimeZone)  Time elapsed: 0.005 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<Central European []Time> but was:<Central European [Standard ]Time>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at junit.framework.Assert.assertEquals(Assert.java:87)
    at org.joda.time.TestDateTimeZone.testGetName_berlin(TestDateTimeZone.java:793)

testGetChronology_Object_Zone(org.joda.time.convert.TestCalendarConverter)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalAccessException: class org.joda.time.convert.TestCalendarConverter cannot access class sun.util.BuddhistCalendar (in module java.base) because module java.base does not export sun.util to unnamed module @1165b38
    at jdk.internal.reflect.Reflection.throwIllegalAccessException(java.base@9-ea/Reflection.java:405)
    at jdk.internal.reflect.Reflection.throwIllegalAccessException(java.base@9-ea/Reflection.java:396)
    at jdk.internal.reflect.Reflection.ensureMemberAccess(java.base@9-ea/Reflection.java:98)
    at java.lang.Class.newInstance(java.base@9-ea/Class.java:560)
    at org.joda.time.convert.TestCalendarConverter.testGetChronology_Object_Zone(TestCalendarConverter.java:122)

testGetChronology_Object_nullChronology(org.joda.time.convert.TestCalendarConverter)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.IllegalAccessException: class org.joda.time.convert.TestCalendarConverter cannot access class sun.util.BuddhistCalendar (in module java.base) because module java.base does not export sun.util to unnamed module @1165b38
    at jdk.internal.reflect.Reflection.throwIllegalAccessException(java.base@9-ea/Reflection.java:405)
    at jdk.internal.reflect.Reflection.throwIllegalAccessException(java.base@9-ea/Reflection.java:396)
    at jdk.internal.reflect.Reflection.ensureMemberAccess(java.base@9-ea/Reflection.java:98)
    at java.lang.Class.newInstance(java.base@9-ea/Class.java:560)
    at org.joda.time.convert.TestCalendarConverter.testGetChronology_Object_nullChronology(TestCalendarConverter.java:153)

testZoneShortNameNearTransition(org.joda.time.format.TestDateTimeFormatter)  Time elapsed: 0.003 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<...05-10-30 01:00:00.0 [EDT]> but was:<...05-10-30 01:00:00.0 [∅∅∅]>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at junit.framework.Assert.assertEquals(Assert.java:87)
    at org.joda.time.format.TestDateTimeFormatter.testZoneShortNameNearTransition(TestDateTimeFormatter.java:1041)

testFormat_halfdayOfDay(org.joda.time.format.TestDateTimeFormat)  Time elapsed: 0.001 sec  <<< FAILURE!
junit.framework.ComparisonFailure: 2004-06-09T10:20:30.040Z expected:<[AM]> but was:<[am]>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at org.joda.time.format.TestDateTimeFormat.testFormat_halfdayOfDay(TestDateTimeFormat.java:628)

testFormat_zoneText(org.joda.time.format.TestDateTimeFormat)  Time elapsed: 0.001 sec  <<< FAILURE!
junit.framework.ComparisonFailure: 2004-06-09T06:20:30.040-04:00 expected:<[EDT]> but was:<[∅∅∅]>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at org.joda.time.format.TestDateTimeFormat.testFormat_zoneText(TestDateTimeFormat.java:760)

testFormatParse_textHalfdayAM_UK(org.joda.time.format.TestDateTimeFormat)  Time elapsed: 0 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<$06-[PM]-2007> but was:<$06-[pm]-2007>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at junit.framework.Assert.assertEquals(Assert.java:87)
    at org.joda.time.format.TestDateTimeFormat.testFormatParse_textHalfdayAM_UK(TestDateTimeFormat.java:1009)

testFormatParse_textEraBC_France(org.joda.time.format.TestDateTimeFormat)  Time elapsed: 0 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<$[BC]-0001> but was:<$[av. J.-C.]-0001>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at junit.framework.Assert.assertEquals(Assert.java:87)
    at org.joda.time.format.TestDateTimeFormat.testFormatParse_textEraBC_France(TestDateTimeFormat.java:1069)


Results :

Failed tests: 
  org.joda.time.TestDateTimeZone#testGetName_berlin ComparisonFailure expected:<...
  org.joda.time.format.TestDateTimeFormat#testFormatParse_textEraBC_France ComparisonFailure
  org.joda.time.format.TestDateTimeFormat#testFormatParse_textHalfdayAM_UK ComparisonFailure
  org.joda.time.format.TestDateTimeFormat#testFormat_halfdayOfDay ComparisonFailure
  org.joda.time.format.TestDateTimeFormat#testFormat_zoneText ComparisonFailure ...
  org.joda.time.format.TestDateTimeFormatter#testZoneShortNameNearTransition ComparisonFailure
Tests in error: 
  org.joda.time.convert.TestCalendarConverter#testGetChronology_Object_Zone IllegalAccessException
  org.joda.time.convert.TestCalendarConverter#testGetChronology_Object_nullChronology IllegalAccessException

Tests run: 4201, Failures: 6, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.665 s
[INFO] Finished at: 2016-10-09T18:54:52+01:00
[INFO] Final Memory: 10M/35M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project joda-time: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/chrisseaton/Documents/ruby/joda-time/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jodastephen** [comment]
Thanks for looking. I agree that those are going to need work.

**Comment by jodastephen** [comment]
Fixed, thanks
