### ISSUE TITLE
org.joda.time.IllegalInstantException

### ISSUE THREAD

**Issue by chocolatezhu** [JodaOrg/joda-time#425]
### Key information

- Joda-Time version 2.9.9

### Problem description
I new a DateTime, DateTime mStartDate = new DateTime(1991, 4, 14, 0, 0, 0),But it has something wrong,it seem cannot convert the date

### Test case
Here is the log:
// java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=4097, data=null} to activity {com.eebbk.calendar/com.eebbk.studyos.calendar.MainActivity}: org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 1991-04-14T00:00:00.000 (Asia/Shanghai)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4172)
 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4215)
 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
	at android.os.Handler.dispatchMessage(Handler.java:110)
 	at android.os.Looper.loop(Looper.java:203)
 	at android.app.ActivityThread.main(ActivityThread.java:6239)
	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
 Caused by: org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 1991-04-14T00:00:00.000 (Asia/Shanghai)
	at org.joda.time.chrono.ZonedChronology.localToUTC(ZonedChronology.java:157)
 	at org.joda.time.chrono.ZonedChronology.getDateTimeMillis(ZonedChronology.java:122)
 	at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:257)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:198)
 	at org.joda.time.DateTime.<init>(DateTime.java:397)
	at com.eebbk.studyos.calendar.view.slidelayout.ScheduleLayout.onMonthClick(ScheduleLayout.java:166)
	at com.eebbk.studyos.calendar.view.slidelayout.ScheduleLayout$1.onClickDate(ScheduleLayout.java:152)
	at com.eebbk.studyos.calendar.month.MonthCalendarView.onClickThisMonth(MonthCalendarView.java:47)
	at com.eebbk.studyos.calendar.month.MonthView.clickThisMonth(MonthView.java:555)
 	at com.eebbk.studyos.calendar.MainActivity.refreshCalendarView(MainActivity.java:1394)
 	at com.eebbk.studyos.calendar.MainActivity.onActivityResult(MainActivity.java:1435)
 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4168)
	... 9 more

Hope for your reply, thanks!

**Comment by mrjink** [comment]
This is answered in the [FAQ](http://www.joda.org/joda-time/faq.html#illegalinstant).

**Comment by chocolatezhu** [comment]
You mean it's not a bug? Using LocalDateTime insteat of DateTime?

**Comment by jodastephen** [comment]
Not every date-time exists on the local time-line. There are gaps and overlaps around Daylight Saving changes.
