### ISSUE TITLE
DateTime crasches when save as serializable.

### ISSUE THREAD

**Issue by m4xp1** [JodaOrg/joda-time#448]
Version 2.9.9. I tried to keep DateTime in Android as a serializable object and got an error. Obviously, the inner DateTimeZoneBuilder class is not serializable. Please fix it! Thanks!

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.joda.time.DateTime)
                                                     at android.os.Parcel.writeSerializable(Parcel.java:1394)
                                                     at android.os.Parcel.writeValue(Parcel.java:1341)
                                                     at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
                                                     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                     at android.os.Bundle.writeToParcel(Bundle.java:1034)
                                                     at android.os.Parcel.writeBundle(Parcel.java:669)
                                                     at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:148)
                                                     at android.os.Parcel.writeTypedArray(Parcel.java:1197)
                                                     at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:564)
                                                     at android.os.Parcel.writeParcelable(Parcel.java:1363)
                                                     at android.os.Parcel.writeValue(Parcel.java:1268)
                                                     at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
                                                     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                     at android.os.Bundle.writeToParcel(Bundle.java:1034)
                                                     at android.os.Parcel.writeBundle(Parcel.java:669)
                                                     at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2919)
                                                     at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3296)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: java.io.NotSerializableException: org.joda.time.tz.DateTimeZoneBuilder$Recurrence
                                                     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
```

**Comment by jodastephen** [comment]
This occurs because Android does not correctly implement serialization (see `writeReplace()`). As such, there is nothing for Joda-Time to fix.
