### ISSUE TITLE
Change of time in Brazil, DST Start; is in November and not in October

### ISSUE THREAD

**Issue by oskarsa86** [JodaOrg/joda-time#476]
### Key information

- Joda-Time version  2.9.9
- Result of `TimeZone.getDefault()` 
```console
sun.util.calendar.ZoneInfo[id="Europe/Madrid",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=163,lastRule=java.util.SimpleTimeZone[id=Europe/Madrid,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
```

- Result of `DateTimeZone.getDefault()` 
```console
Europe/Madrid
```

### Problem description

From 2018, the change of time in Brazil, DST Start; is in November and not in October
http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/decreto/D9242.htm

### Test case
```java
new DateTime(2018, 10, 21, 0, 0, DateTimeZone.forID("America/Sao_Paulo"))
```
```console
org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2018-10-21T00:00:00.000 (America/Sao_Paulo)
  at org.joda.time.chrono.ZonedChronology.localToUTC(ZonedChronology.java:157)
  at org.joda.time.chrono.ZonedChronology.getDateTimeMillis(ZonedChronology.java:122)
  at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
  at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:257)
  at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:226)
  at org.joda.time.DateTime.<init>(DateTime.java:347)
  ... 36 elided
```

```java
new DateTime(2018, 11, 4, 0, 0, DateTimeZone.forID("America/Sao_Paulo"))
```
```console
2018-11-04T00:00:00.000-02:00 <--- Does not exist
```

**Comment by hkotsubo** [comment]
Timezone data is not updated automatically, [you must do it yourself](http://www.joda.org/joda-time/tz_update.html).

**Comment by jodastephen** [comment]
Joda-Time v2.10 is now released.
