### ISSUE TITLE
Ensure compatibility with Graal

### ISSUE THREAD

**Issue by mavilein** [JodaOrg/joda-time#478]
Hey there,

first of all i would like to thank for developing this software! I am a backend engineer at [Prisma](https://github.com/prismagraphql/prisma). I am opening this issue as we are a happy user of this library and would like it to be compatible with Graal.

**What is Graal?**

Graal is a collection of tools. For one it is a JVM replacement that does not only run Java Bytecode but also other languages like Javascript or Ruby. It also comes with a tool called native image. This allows to **compile a JAR into a standalone binary**.

We would like to turn our Prisma Server into a lightweight binary with Graal.

However the Graal native image tool comes with some limitations. Some features of the JVM are not supported, e.g. the support for reflection is limited because it is not a good fit with ahead of time compilation. Therefore we created a [test suite](https://github.com/prismagraphql/graal-compatibility) to check the compatibility of our used dependencies with Graal. For each dependency we tried to come up with a super small program and see whether it compiles with Graal or not.

The program to test compatibility with this library can be found [here](https://github.com/prismagraphql/graal-compatibility/blob/master/other/src/main/scala/Main.scala).

**What's the problem we have hit?**
When running with `-H:+ReportUnsupportedElementsAtRuntime`:

```
java.io.IOException: Resource not found: "org/joda/time/tz/data/Europe/Berlin" ClassLoader: java.lang.ClassLoader@1094312b0
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:216)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:231)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:162)
	at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:354)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:157)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:61)
	at org.joda.time.DateTime.<init>(DateTime.java:171)
	at Main$.main(Main.scala:26)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
```

When running without `-H:+ReportUnsupportedElementsAtRuntime`:

```
java.io.IOException: Resource not found: "org/joda/time/tz/data/Europe/Berlin" ClassLoader: java.lang.ClassLoader@104b21c10
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:216)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:231)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:162)
	at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:354)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:157)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:61)
	at org.joda.time.DateTime.<init>(DateTime.java:171)
	at Main$.main(Main.scala:26)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
```

**Note**: The Graal compilation terminates on the first encountered error. Therefore there might be more problems that need to be addressed.

**How can incompatibilities with Graal be fixed?**

Here is a [blog post](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) by the Graal team that explains how the native image tool is working and how they were able to compile a server built on top of netty into a binary.

We ran this test with Graal `1.0.0-rc5`. We used `joda-time` in version `2.9.4` and `joda-convert` in version `1.7`.
There is documented way to add resources to a native image generated with Graal. I wonder if those configuration settings could be documented so not every user needs to repeat his process.

**Comment by jodastephen** [comment]
Not sure what you're hoping to change in the repo? If you want to add some docs, feel free to raise a PR.

**Comment by dpetrick** [comment]
It works with the following line in `native-image`: `-H:IncludeResources=org/joda/time/tz/data/.*`

**Comment by jodastephen** [comment]
Thanks for the solution, I think this issue acts as effective documentation.
