### ISSUE TITLE
Import of tzdata 2020f and 2021a with ZoneInfoCompiler fails

### ISSUE THREAD

**Issue by hayos** [JodaOrg/joda-time#552]
### Key information

- Joda-Time version: 2.10.8 and 2.7.0
- Result of `TimeZone.getDefault()`: N/A
- Result of `DateTimeZone.getDefault()`: N/A
System runs in Germany.

### Problem description
When importing tzdata 2020f (and broken 2020e) or 2021a into ZoneInfoCompiler, an error occurs. Here is the verbose output.

Writing Asia/Makassar
Writing Asia/Jayapura
Writing Asia/Tehran
Writing Asia/Baghdad
Exception in thread "main" org.joda.time.IllegalFieldValueException: Value 31 for dayOfMonth must be in the range [1,30]
at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)
at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:79)
at org.joda.time.tz.DateTimeZoneBuilder$OfYear.setDayOfMonth(DateTimeZoneBuilder.java:707)
at org.joda.time.tz.DateTimeZoneBuilder$OfYear.setDayOfMonthNext(DateTimeZoneBuilder.java:672)
at org.joda.time.tz.DateTimeZoneBuilder$OfYear.next(DateTimeZoneBuilder.java:565)
at org.joda.time.tz.DateTimeZoneBuilder$Recurrence.next(DateTimeZoneBuilder.java:761)
at org.joda.time.tz.DateTimeZoneBuilder$Rule.next(DateTimeZoneBuilder.java:865)
at org.joda.time.tz.DateTimeZoneBuilder$RuleSet.nextTransition(DateTimeZoneBuilder.java:1094)
at org.joda.time.tz.DateTimeZoneBuilder$RuleSet.firstTransition(DateTimeZoneBuilder.java:1032)
at org.joda.time.tz.DateTimeZoneBuilder.toDateTimeZone(DateTimeZoneBuilder.java:351)
at org.joda.time.tz.ZoneInfoCompiler.compile(ZoneInfoCompiler.java:394)
at org.joda.time.tz.ZoneInfoCompiler.main(ZoneInfoCompiler.java:137)

FAILURE: Build failed with an exception.

### Test case
Standard tzdata import with ZoneInfoCompiler via main.

**Comment by jodastephen** [comment]
This problem is fixed in the latest version 2.10.9

**Comment by jarizdelgado238405** [comment]
Hi @jodastephen  Im importing tzdata 2022g with ZoneInfoCompiler fails. it is giving me the same error showed here.. Im tried with joda-time- versions  2.10.9, 2.10.10 ,2.12.2 and any works.What could i do?

Writing Asia/Baghdad
While executing [invoke] encountered [org.joda.time.IllegalFieldValueException] : [Value 31 for dayOfMonth must be in the range [1,30] at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:215)]
	at com.tibco.plugin.java.JavaActivity.eval(Unknown Source)
	at com.tibco.pe.plugin.Activity.eval(Unknown Source)
	at com.tibco.pe.core.TaskImpl.eval(Unknown Source)
	at com.tibco.pe.core.Job.a(Unknown Source)
	at com.tibco.pe.core.Job.k(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.a(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.run(Unknown Source)

**Comment by jarizdelgado238405** [comment]
@jodastephen  I found error i was loading a joda version 1.6.2 in classhpath it was causing this issue again..
Thanks anyway.
