### ISSUE TITLE
org.joda.time.TestDateTimeZone tests failed

### ISSUE THREAD

**Issue by didiksupriadi41** [JodaOrg/joda-time#563]
### Key information

- Joda-Time version
`2.10.10`
- Result of `TimeZone.getDefault()`
`sun.util.calendar.ZoneInfo[id="Asia/Jakarta",offset=25200000,dstSavings=0,useDaylight=false,transitions=9,lastRule=null]`
- Result of `DateTimeZone.getDefault()`
`Asia/Jakarta`

### Problem description
The tests don't seem to pass.
Both java LTS version have this failure. (see below)

### Test case
**Java 11**
```
$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)
$ javac -version
javac 11.0.12
....
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ joda-time ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.joda.time.TestAllPackages

TestBuddhistChronology.testCalendar

TestCopticChronology.testCalendar

TestEthiopicChronology.testCalendar

TestIslamicChronology.testCalendar

Testing Gregorian chronology over 1000 iterations
100% complete (i=1000)

Testing Julian chronology over 1000 iterations
100% complete (i=1000)
Writing zoneinfo files
Writing ZoneInfoMap
[ERROR] Tests run: 4238, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 10.182 s <<< FAILURE! - in org.joda.time.TestAllPackages
[ERROR] org.joda.time.TestDateTimeZone.testGetName_berlin_english  Time elapsed: 0.017 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<Central European []Time> but was:<Central European [Standard ]Time>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:260)
	at org.joda.time.TestDateTimeZone.testGetName_berlin_english(TestDateTimeZone.java:813)

[ERROR] org.joda.time.TestDateTimeZone.testGetName_berlin_german  Time elapsed: 0.039 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<Mitteleuropäische [Z]eit> but was:<Mitteleuropäische [Normalz]eit>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:260)
	at org.joda.time.TestDateTimeZone.testGetName_berlin_german(TestDateTimeZone.java:824)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   org.joda.time.TestDateTimeZone#testGetName_berlin_english  expected:<Central E...
[ERROR]   org.joda.time.TestDateTimeZone#testGetName_berlin_german  expected:<Mitteleuro...
[INFO] 
[ERROR] Tests run: 4238, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Joda-Time
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2021-08-25T09:19:01+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project joda-time: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/chronoelves/rpmbuild/BUILD/joda-time-2.10.10/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
**Java 8**
```
$ java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)
$ javac -version
javac 1.8.0_302
....
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ joda-time ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.joda.time.TestAllPackages

TestBuddhistChronology.testCalendar

TestCopticChronology.testCalendar

TestEthiopicChronology.testCalendar

TestIslamicChronology.testCalendar

Testing Gregorian chronology over 1000 iterations
100% complete (i=1000)

Testing Julian chronology over 1000 iterations
100% complete (i=1000)
Writing zoneinfo files
Writing ZoneInfoMap
[ERROR] Tests run: 4238, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 9.527 s <<< FAILURE! - in org.joda.time.TestAllPackages
[ERROR] org.joda.time.TestDateTimeZone.testGetName_berlin_english  Time elapsed: 0.026 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<Central European []Time> but was:<Central European [Standard ]Time>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:260)
	at org.joda.time.TestDateTimeZone.testGetName_berlin_english(TestDateTimeZone.java:813)

[ERROR] org.joda.time.TestDateTimeZone.testGetName_berlin_german  Time elapsed: 0.035 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<Mitteleuropäische [Z]eit> but was:<Mitteleuropäische [Normalz]eit>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:260)
	at org.joda.time.TestDateTimeZone.testGetName_berlin_german(TestDateTimeZone.java:824)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   org.joda.time.TestDateTimeZone#testGetName_berlin_english  expected:<Central E...
[ERROR]   org.joda.time.TestDateTimeZone#testGetName_berlin_german  expected:<Mitteleuro...
[INFO] 
[ERROR] Tests run: 4238, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Joda-Time
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2021-08-25T12:15:38+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project joda-time: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/chronoelves/rpmbuild/BUILD/joda-time-2.10.10/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by didiksupriadi41** [comment]
(might useful) #394

**Comment by jodastephen** [comment]
PR merged
