### ISSUE TITLE
Period instance after protostuff deserialize throw "Period does not support field 'days'" exception.

### ISSUE THREAD

**Issue by longhow** [JodaOrg/joda-time#581]
### Key information

- Joda-Time version：
- 2.9.9

- Result of `TimeZone.getDefault()`
-sun.util.calendar.ZoneInfo[id="Asia/Shanghai",offset=28800000,dstSavings=0,useDaylight=false,transitions=19,lastRule=null]

- Result of `DateTimeZone.getDefault()`
- Asia/Shanghai

### Problem description
Period instance after protostuff deserialize throw "Period does not support field 'days'" exception.

### Test case
   public static void main(String[] args) {
        /*
        instance period1 after protostuff deserialize becomes instance period2,
        execute 'Period period3 = Period.parse("P2D")' and throw exception
         */
        try {
            Period period1 = Period.parse("P10D");

            RuntimeSchema<Period> schema = RuntimeSchema.createFrom(Period.class);
            byte[] bytes = ProtostuffIOUtil.toByteArray(period1, schema, LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE));

            Period period2 = schema.newMessage();
            ProtostuffIOUtil.mergeFrom(bytes, period2, schema);

            Period period3 = Period.parse("P2D");

        } catch (Exception e) {
            e.printStackTrace();
            /*
            java.lang.IllegalArgumentException: Period does not support field 'days'
                at org.joda.time.base.BasePeriod.setFieldInto(BasePeriod.java:489)
                at org.joda.time.base.BasePeriod.setField(BasePeriod.java:474)
                at org.joda.time.MutablePeriod.setDays(MutablePeriod.java:887)
                at org.joda.time.format.PeriodFormatterBuilder$FieldFormatter.setFieldValue(PeriodFormatterBuilder.java:1843)
                at org.joda.time.format.PeriodFormatterBuilder$FieldFormatter.parseInto(PeriodFormatterBuilder.java:1634)
                at org.joda.time.format.PeriodFormatterBuilder$Composite.parseInto(PeriodFormatterBuilder.java:2162)
                at org.joda.time.format.PeriodFormatterBuilder$Separator.parseInto(PeriodFormatterBuilder.java:2035)
                at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:322)
                at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:308)
                at org.joda.time.Period.parse(Period.java:92)
                at org.joda.time.Period.parse(Period.java:81)
             */
        }
    }

ps:dependency:
<dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.9.9</version>
        </dependency>
        <dependency>
            <groupId>io.protostuff</groupId>
            <artifactId>protostuff-api</artifactId>
            <version>1.7.4</version>
        </dependency>
        <dependency>
            <groupId>io.protostuff</groupId>
            <artifactId>protostuff-core</artifactId>
            <version>1.7.4</version>
        </dependency>
        <dependency>
            <groupId>io.protostuff</groupId>
            <artifactId>protostuff-runtime</artifactId>
            <version>1.7.4</version>
        </dependency>

**Comment by longhow** [comment]
PeriodType's indexOf(DurationFieldType type) memthod use "==" to compare "iTypes[i] == type"，after protostuff deserialize，PeriodType's DurationFieldType[] iTypes are changed，and  "==" compare reture false
