### ISSUE TITLE
Joda-time Not Able to Interpret Specific Dates and Giving Exception

### ISSUE THREAD

**Issue by jahar-tyagi** [JodaOrg/joda-time#584]
Hi Stephen,

Hope your are doing great.

We are using Joda-Time extensively in our project (currently 2.9.9 version). Lately We learned that Joda-time is required to be updated to support [tzdata2021e]. So we updated to joda-time-2.10.13 as suggested in [579](https://github.com/JodaOrg/joda-time/issues/579) .

Now we are facing a problem where Joda-time is not able to interpret specific dates and giving exception. Below is the usecase.

**Timezone: Asia/Amman**
**Joda-time version: joda-time-2.10.13.jar**

```
import org.joda.time.DateTime;
public class Test {
	public static void main(String[] args) {
		System.out.println("Current TimeZone: " + new DateTime().getZone() + " Current Datetime : " + new DateTime().now());
                // Issue Occurs on all dates when DST about to begin e.g. 2023-02-24 , 2024-03-01 , 2025-02-28 etc
		DateTime theFutureDateTime = new DateTime("2023-02-24");
		System.out.println("Date :  "+theFutureDateTime);	
	}
}
```

**Output**

```
Current TimeZone: Asia/Amman Current Datetime : 2022-03-23T14:30:41.352+03:00
Exception in thread "main" org.joda.time.IllegalInstantException: Cannot parse "2023-02-24": Illegal instant due to time zone offset transition (Asia/Amman)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:473)
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:182)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
	at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:173)
	at org.joda.time.DateTime.<init>(DateTime.java:257)
	at myprac.Test.main(Test.java:8)
```

Same case happens in Joda-time2.9.9 version when the date is '2023-03-31'. 

Request you to please look into this and provide your inputs.

**Comment by jodastephen** [comment]
This is the normal behaviour of Joda-Time. Joda-Time does not allow you to create an instance that does not actually occur, and for Asia/Amman midnight does not occur on those dates. See the [first FAQ](https://www.joda.org/joda-time/faq.html) for more info and possible solutions.

Note that `java.time.*` solves this problem in a better way (without exceptions).
