### ISSUE TITLE
tz2022c update for joda time is failing with latest joda-time release 2.11.1

### ISSUE THREAD

**Issue by chakrirc8** [JodaOrg/joda-time#633]
While applying tzdata2022c on linux machine, joda-time update is failing with below error

Joda-time version used is 2.11.1

JODA TZ version : 2022a --> 2022c ... Exception in thread "main" java.lang.ClassCastException: org.joda.time.UTCDateTimeZone cannot be cast to org.joda.time.tz.DateTimeZoneBuilder$PrecalculatedZone
        at org.joda.time.tz.DateTimeZoneBuilder.writeTo(DateTimeZoneBuilder.java:481)
        at org.joda.time.tz.DateTimeZoneBuilder.writeTo(DateTimeZoneBuilder.java:453)
        at org.joda.time.tz.ZoneInfoCompiler.writeZone(ZoneInfoCompiler.java:485)
        at org.joda.time.tz.ZoneInfoCompiler.compile(ZoneInfoCompiler.java:423)
        at org.joda.time.tz.ZoneInfoCompiler.main(ZoneInfoCompiler.java:126)
Failed
 | Writing zoneinfo files
 | Fixed negative save values for rule 'Morocco'
 | Fixed negative save values for rule 'Morocco'
 | Fixed negative save values for rule 'Morocco'
 | Fixed negative save values for rule 'Morocco'
 | Fixed negative save values for rule 'Morocco'
 | Fixed negative save values for rule 'Namibia'
 | Fixed negative save values for rule 'Eire'
 | Fixed negative save values for rule 'Eire'

**Comment by jodastephen** [comment]
Just to note that the latest release of Joda-Time includes the 2022c data.

**Comment by jodastephen** [comment]
Closing with solution to upgrade to a later version
